name: test-install-action
run-name: ${{ github.actor }} is testing ./run install
on: [push]
jobs:
  run-install-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Running ./run install..."
      - run: ./run install
      - run: echo "Running ./run test..."
      - run: ./run test
      - run: echo "This job's status is ${{ job.status }}."
